In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from sklearn import linear_model

In [2]:
reg=linear_model.LinearRegression()

In [14]:
dict={"area":[2600,3000,3200,3600,400] , "bedrooms":[3,4,3,3,5], "age":[20,15,18,30,8], "price":[550000,565000,610000,595000,760000]}

In [15]:
df= pd.DataFrame.from_dict(dict)

In [16]:
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4   400         5    8  760000

In [17]:
x=pd.DataFrame({"area":[2600,3000,3200,3600,400] , "bedrooms":[3,4,3,3,5], "age":[20,15,18,30,8], "price":[550000,565000,610000,595000,760000]})

In [18]:
x

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4   400         5    8  760000

In [19]:
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4   400         5    8  760000

In [27]:
reg=linear_model.LinearRegression()
dt_model=reg.fit(df[["area",'bedrooms',"age"]],df.price)

In [24]:
dt_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
dt_model.coef_

array([  -54.73075625, 35161.63065496,  3723.4132343 ])

In [28]:
reg.coef_

array([  -54.73075625, 35161.63065496,  3723.4132343 ])

In [29]:
reg.intercept_

561762.7447670491

In [30]:
dt_model.intercept_

561762.7447670491

In [31]:
dt_model.predict([[3000,3,14]])

array([555183.15327481])

In [32]:
reg.predict([[3000,3,14]])

array([555183.15327481])